import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css';
import { quizCategories } from '@/data/quiz';
import { useRouter } from 'next/navigation';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Quiz App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Select a quiz category</h1>

        {/* Quiz Categories */}
        <div className={styles.categories}>
          {quizCategories.map(({ id, title, image, slug, duration }) => (
            <blockquote 
              key={id} 
              onClick={() => router.push({
                pathname: "quiz/[slug]",
                query: {
                  slug: slug
                }
              })}
              className={styles.categoryItem}
            >
              <Image 
                src={image}
                alt={title}
                className={styles.categoryItemImage}
              />

              <h5>{title}</h5>
              <span>{duration}</span>
              <button>Start quiz</button>
            </blockquote>
          ))}
        </div>
      </main>
    </>
  )
}
